# fetch_fonts.py
# Vendors the panel's webfonts into panel/static/fonts/ and regenerates
# panel/static/fonts.css.
#
# The panel serves its own fonts rather than linking a font CDN: a Wikimedia
# tool should not hand its visitors' IP addresses to a third party.
#
# Run from the repo root:  python scripts/fetch_fonts.py

import pathlib
import re
import urllib.request

# Google Fonts serves woff2 only to browsers that advertise support.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

# (css family name, Google Fonts spec, subsets to keep)
#   Inter            – interface text, per the Feather style guide
#   IBMPlexMono      – log output, where column alignment carries meaning
#   NotoSansBengali  – Bengali OCR text, which is most of what the log shows
FAMILIES = [
    ("Inter", "Inter:wght@400;500;600;700", ("latin",)),
    ("IBMPlexMono", "IBM+Plex+Mono:wght@400", ("latin",)),
    ("NotoSansBengali", "Noto+Sans+Bengali:wght@400", ("bengali",)),
]

STATIC = pathlib.Path(__file__).resolve().parent.parent / 'panel' / 'static'
HEADER = """/* Generated by scripts/fetch_fonts.py — do not edit by hand.
 *
 * Served from this tool, never a font CDN, so the panel makes no third-party
 * requests on a visitor's behalf.
 */
"""


def main():
    fonts_dir = STATIC / 'fonts'
    fonts_dir.mkdir(parents=True, exist_ok=True)
    for stale in fonts_dir.glob('*.woff2'):
        stale.unlink()

    blocks = [HEADER]
    for family, spec, subsets in FAMILIES:
        url = f"https://fonts.googleapis.com/css2?family={spec}&display=swap"
        css = urllib.request.urlopen(
            urllib.request.Request(url, headers={'User-Agent': UA}), timeout=30
        ).read().decode()

        # Google prefixes each @font-face with a /* subset */ comment.
        faces = re.findall(r"/\*\s*([\w\-\[\]]+)\s*\*/\s*(@font-face\s*\{[^}]+\})", css)
        kept = 0
        for subset, face in faces:
            if not any(s in subset for s in subsets):
                continue
            src = re.search(r"url\((https://[^)]+\.woff2)\)", face).group(1)
            weight = re.search(r"font-weight:\s*([^;]+);", face).group(1).strip()
            urange = re.search(r"unicode-range:\s*([^;]+);", face).group(1).strip()

            name = f"{family}-{subset}.woff2"
            (fonts_dir / name).write_bytes(
                urllib.request.urlopen(src, timeout=30).read())
            blocks.append(
                "@font-face {\n"
                f"  font-family: '{family}';\n"
                "  font-style: normal;\n"
                f"  font-weight: {weight};\n"
                "  font-display: swap;\n"
                f"  src: url('fonts/{name}') format('woff2');\n"
                f"  unicode-range: {urange};\n"
                "}\n")
            kept += 1
        print(f"{family}: {kept} face(s)")

    (STATIC / 'fonts.css').write_text("\n".join(blocks), encoding='utf-8')
    total = sum(f.stat().st_size for f in fonts_dir.glob('*.woff2'))
    print(f"wrote fonts.css, {total // 1024} KB of woff2")


if __name__ == '__main__':
    main()
